const QUERY_KEY = {
  CAMPAGIN: {
    LIST: "CAMPAGIN_LIST",
    LIST_CUSTOMER: "CAMPAIGN_CUSTOMER_LIST",
    LIST_GIFT: "CAMPAIGN_GIFT_LIST",
    LIST_LUCKY_HISTORY: "CAMPAIGN_LUCKY_LIST",
    DETAIL_NUMBER: "CAMPAIGN_DETAIL_NUMBER",
  },
};

export default QUERY_KEY;
